In [172]:
import pandas as pd
import numpy as np

In [38]:
#list = [result_2014,result_2015,result_2016,result_2017,result_2018,result_2019]
arg2014 = pd.read_csv('result_2014.csv',index_col=False)
arg2014 = arg2014.drop(arg2014.columns[0], axis=1).sort_values(by = ['SQLDATEE']) 

arg2015 = pd.read_csv('result_2015.csv',index_col=False)
arg2015 = arg2015.drop(arg2015.columns[0], axis=1).sort_values(by = ['SQLDATEE']) 

arg2016 = pd.read_csv('result_2016.csv',index_col=False)
arg2016 = arg2016.drop(arg2016.columns[0], axis=1).sort_values(by = ['SQLDATEE']) 

arg2017 = pd.read_csv('result_2017.csv',index_col=False)
arg2017 = arg2017.drop(arg2017.columns[0], axis=1).sort_values(by = ['SQLDATEE']) 

arg2018 = pd.read_csv('result_2018.csv',index_col=False)
arg2018 = arg2018.drop(arg2018.columns[0], axis=1).sort_values(by = ['SQLDATEE']) 

arg2019 = pd.read_csv('result_2019.csv',index_col=False)
arg2019 = arg2019.drop(arg2019.columns[0], axis=1).sort_values(by = ['SQLDATEE'])

In [173]:
arg = pd.concat([arg2014,arg2015,arg2016,arg2017,arg2018,arg2019])
orignical_data = arg.copy()

In [66]:
orignical_data.head()

,SOURCEURL,GoldsteinScale,NumMentions,NumSources,NumArticles,AvgTone,SQLDATEE
517,http://www.20minutos.es/noticia/2381548/0/vill...,2.350000,10.0,1.0,10.0,1.796407,20140219
281,http://lavoz901.com.ar/despachos.asp?cod_des=2...,3.400000,10.0,1.0,10.0,-6.097561,20140219
990,http://www.elcomercial.com.ar/index.php?option...,8.000000,5.0,1.0,5.0,1.265823,20140219
962,http://www.dw.de/thousands-march-in-silent-ral...,-3.333333,4.0,1.0,4.0,-6.479218,20140219
1726,http://www.perishablenews.com/index.php?articl...,6.400000,10.0,1.0,10.0,2.672606,20140219

In [122]:
df = arg[['SQLDATEE','GoldsteinScale','NumMentions','NumSources','NumArticles','AvgTone']].reset_index(drop=True)
df.columns = ['DATE','GoldsteinScale','NumMentions','NumSources','NumArticles','AvgTone']

In [160]:
agg1 = df.groupby('DATE').mean().reset_index()

In [161]:
agg2 = df[['AvgTone','DATE']].groupby('DATE').count().rename(columns = {'AvgTone':'NumNews'}).reset_index()

In [162]:
data = pd.merge(agg1, agg2, on='DATE')

In [163]:
data.head()

,DATE,GoldsteinScale,NumMentions,NumSources,NumArticles,AvgTone,NumNews
0,20140219,0.451282,6.538462,1.000000,6.538462,-2.975862,13
1,20140220,1.996429,5.833333,1.071429,5.833333,-2.587891,14
2,20140221,4.394444,6.148148,1.000000,5.592593,-2.688826,9
3,20140222,0.788095,8.666667,1.000000,8.666667,3.159957,6
4,20140223,2.726923,8.250000,1.000000,8.250000,-0.974292,13

In [165]:
l = data['NumNews'].values.tolist()
Target = ['',]
for i,j in zip(range(0,len(l)-1), range(1,len(l))):
    if l[i] < l[j]:
        Target.append(1)
    else:
        Target.append(-1)

In [166]:
Target = pd.DataFrame({'Target':Target})

In [167]:
final_data = pd.concat([data,Target],axis=1)

In [169]:
final_data

,DATE,GoldsteinScale,NumMentions,NumSources,NumArticles,AvgTone,NumNews,Target
0,20140219,0.451282,6.538462,1.000000,6.538462,-2.975862,13,
1,20140220,1.996429,5.833333,1.071429,5.833333,-2.587891,14,1
2,20140221,4.394444,6.148148,1.000000,5.592593,-2.688826,9,-1
3,20140222,0.788095,8.666667,1.000000,8.666667,3.159957,6,-1
4,20140223,2.726923,8.250000,1.000000,8.250000,-0.974292,13,1
5,20140224,2.414286,6.535714,1.000000,6.535714,-2.061723,7,-1
6,20140225,2.433333,3.833333,1.166667,3.833333,-5.548919,6,-1
7,20140226,1.315000,8.100000,1.100000,8.100000,-2.533706,10,1
8,20140227,2.077778,7.527778,1.000000,7.527778,-0.415180,12,1
9,20140228,0.014732,5.613839,1.000000,5.613839,-1.154467,8,-1
10,20140301,1.133333,5.000000,1.000000,5.000000,0.446590,3,-1
11,20140302,0.060000,5.566667,1.000000,5.566667,0.266338,10,1
12,20140303,0.066667,10.027778,1.000000,10.027778,-1.947449,12,1
13,20140304,-0.096875,9.854167,1.375000,9.854167,-2.797379,16,1
14,20140305,-1.687500,4.400000,1.000000,4.375000,-2.363766,8,-1
15,20140306,-0.125641,4.812821,1.000000,4.566667,-1.554705,13,1
16,20140307,0.371429,7.357143,1.000000,7.357143,-1.823275,4,-1
17,20140308,0.928571,7.857143,1.000000,7.857143,-0.936946,12,1
18,20140309,1.526923,8.115385,1.153846,8.115385,-2.211503,13,1
19,20140310,0.715747,6.608766,1.071429,6.608766,-2.221116,28,1
20,20140311,1.231250,7.312500,1.187500,7.312500,-2.699147,16,-1
21,20140312,0.160000,4.070000,1.050000,4.070000,-2.312344,10,-1
22,20140313,2.280000,9.500000,1.000000,9.500000,-1.407009,10,-1
23,20140314,5.400000,8.000000,1.000000,8.000000,0.121387,9,-1
24,20140315,3.850000,10.750000,1.000000,10.750000,0.100105,4,-1
25,20140316,3.328571,5.952381,1.000000,5.952381,-1.891240,7,1
26,20140317,1.868182,6.363636,1.000000,6.363636,-0.838905,11,1
27,20140318,0.552083,7.500000,1.000000,7.500000,-4.097116,8,-1
28,20140319,1.277273,7.484848,1.000000,7.484848,-0.589358,11,1
29,20140320,0.833333,8.138889,1.166667,8.138889,-0.406866,6,-1
...,...,...,...,...,...,...,...,...
1919,20190526,1.397634,7.689156,1.019274,7.548872,-0.885349,441,-1
1920,20190527,0.958481,7.609686,1.014962,7.505870,-1.088964,581,1
1921,20190528,1.161430,7.946312,1.042741,7.793183,-1.172637,698,1
1922,20190529,0.500135,8.140854,1.022974,7.942913,-1.574245,769,1
1923,20190530,0.649800,7.847875,1.018134,7.705215,-1.639951,693,-1
1924,20190531,0.821713,7.564764,1.026056,7.460022,-1.269093,710,1
1925,20190601,0.679710,7.336733,1.005423,7.215437,-1.008765,461,-1
1926,20190602,0.874084,7.205767,1.009158,7.082724,-1.088792,455,-1
1927,20190603,1.066983,7.872485,1.009048,7.680683,-1.192942,571,1
1928,20190604,0.767431,7.882711,1.061492,7.756699,-1.350389,657,1
1929,20190605,1.027202,7.833114,1.024734,7.748905,-0.805441,690,1
1930,20190606,1.259776,7.056384,1.018697,6.945750,-0.647588,855,1
1931,20190607,1.225026,7.222768,1.019508,7.092461,-0.854755,850,-1
1932,20190608,1.015735,7.427472,1.025562,7.313216,-1.153730,534,-1
1933,20190609,1.279016,7.268509,1.011066,7.070819,-1.029380,497,-1
1934,20190610,1.407658,7.219226,1.010683,7.054349,-0.757459,713,1
1935,20190611,1.018725,7.576427,1.023323,7.443294,-0.942325,791,1
1936,20190612,1.138588,7.389120,1.020961,7.264975,-0.727409,794,1
1937,20190613,1.295287,7.442239,1.020519,7.361750,-0.433813,822,1
1938,20190614,0.979114,7.343660,1.028704,7.261305,-1.238673,720,-1
1939,20190615,1.113482,7.561315,1.015406,7.472820,-0.896359,476,-1
1940,20190616,0.886934,7.457315,1.052890,7.349539,-1.735868,617,1
1941,20190617,0.882831,7.317103,1.022568,7.190650,-1.774515,724,1
1942,20190618,1.384428,7.477046,1.023572,7.394995,-1.007780,683,-1
1943,20190619,1.158042,7.285959,1.006974,7.195358,-0.887435,666,-1
1944,20190620,0.825774,7.342714,1.012249,7.256594,-0.590881,657,-1
1945,20190621,1.090542,7.547707,1.042420,7.373861,-0.749676,664,1
1946,20190622,1.261285,7.473265,1.044753,7.267667,-0.695831,486,-1
1947,20190623,1.072568,7.276040,1.012045,7.173401,-0.480150,577,1
1948,20190624,0.921104,7.169331,1.023231,7.085881,-0.973335,617,1

In [170]:
final_data.shape

(1949, 8)

In [171]:
final_data.to_csv('final_data.csv')