In [1]:
import pandas as pd
import numpy as np
from newspaper import Article
from datetime import datetime
import pickle
from langdetect import detect
from preprocessing import *

In [2]:
df = pd.read_csv('argentina.csv').drop(['Unnamed: 0'],axis=1)

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,37,38,39,40,43,45,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df = df.sort_values(by=['SQLDATE'])

In [4]:
df.head()

,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
32170,413369893,20150301,201503,2015,2015.1671,PTY,POLITICIAN,NaN,NaN,NaN,...,1,Argentina,AR,AR,NaN,-34.0000,-64.0000,AR,20150301193000,http://www.lapoliticaonline.com/nota/87318-la-...
784394,413362154,20150301,201503,2015,2015.1671,ITA,TYROL,ITA,NaN,NaN,...,4,"Saenz Pena, Buenos Aires, Argentina",AR,AR01,22379,-34.6005,-58.5301,-1011216,20150301183000,http://portal1.chaco.gov.ar/noticia/32308/la-i...
784395,413361856,20150301,201503,2015,2015.1671,ARGCVL,ARGENTINA,ARG,NaN,NaN,...,4,"Villa Angela, Chaco, Argentina",AR,AR03,4542,-27.5738,-60.7153,-1018843,20150301183000,http://portal1.chaco.gov.ar/noticia/32308/la-i...
499797,413311566,20150301,201503,2015,2015.1671,CHRCTH,THE POPE,NaN,NaN,NaN,...,1,Mexico,MX,MX,NaN,23.0000,-102.0000,MX,20150301123000,http://www.romandie.com/news/Visite-dEtat-du-p...
499798,413380282,20150301,201503,2015,2015.1671,ARG,ARGENTINA,ARG,NaN,NaN,...,1,Mexico,MX,MX,NaN,23.0000,-102.0000,MX,20150301210000,http://www.vavel.com/mx/futbol-mexicano/liga-m...

In [5]:
df.shape

(844025, 61)

In [6]:
arg201503 = df[df['MonthYear'] == 201503 ]
arg201504 = df[df['MonthYear'] == 201504 ]
arg201505 = df[df['MonthYear'] == 201505 ]
arg201506 = df[df['MonthYear'] == 201506 ]
arg201507 = df[df['MonthYear'] == 201507 ]
arg201508 = df[df['MonthYear'] == 201508 ]
arg201509 = df[df['MonthYear'] == 201509 ]
arg201510 = df[df['MonthYear'] == 201510 ]
arg201511 = df[df['MonthYear'] == 201511 ]
arg201512 = df[df['MonthYear'] == 201512 ]
arg201601 = df[df['MonthYear'] == 201601 ]
arg201602 = df[df['MonthYear'] == 201602 ]
arg201603 = df[df['MonthYear'] == 201603 ]

In [12]:
arg201503.to_csv('arg201503.csv')
arg201504.to_csv('arg201504.csv')
arg201505.to_csv('arg201505.csv')
arg201506.to_csv('arg201506.csv')
arg201507.to_csv('arg201507.csv')
arg201508.to_csv('arg201508.csv')
arg201509.to_csv('arg201509.csv')
arg201510.to_csv('arg201510.csv')
arg201511.to_csv('arg201511.csv')
arg201512.to_csv('arg201512.csv')
arg201601.to_csv('arg201601.csv')
arg201602.to_csv('arg201602.csv')
arg201603.to_csv('arg201603.csv')

### pickle cleaning

In [2]:
pickle_cleaning('arg201503.csv','arg201503.p')
pickle_cleaning('arg201504.csv','arg201504.p')
pickle_cleaning('arg201505.csv','arg201505.p')
pickle_cleaning('arg201506.csv','arg201506.p')
pickle_cleaning('arg201507.csv','arg201507.p')
pickle_cleaning('arg201508.csv','arg201508.p')
pickle_cleaning('arg201509.csv','arg201509.p')
pickle_cleaning('arg201510.csv','arg201510.p')
pickle_cleaning('arg201511.csv','arg201511.p')
pickle_cleaning('arg201512.csv','arg201512.p')
pickle_cleaning('arg201601.csv','arg201601.p')
pickle_cleaning('arg201602.csv','arg201602.p')
pickle_cleaning('arg201603.csv','arg201603.p')

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2903: DtypeWarning: Columns (15,25) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

There are 26820 items in News.
26820

There are 24495 items in News.
24495

There are 19071 items in News.
19071

There are 21669 items in News.
21669

There are 27450 items in News.
27450

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2903: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

There are 24455 items in News.
24455

There are 29956 items in News.
29956

There are 25744 items in News.
25744

There are 26453 items in News.
26453

There are 27330 items in News.
27330

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2903: DtypeWarning: Columns (22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

There are 26646 items in News.
26646

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2903: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

There are 27900 items in News.
27900

C:\Users\sheny\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2909: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

There are 35211 items in News.
35211

### text_downloading

In [ ]:
text_downloading('arg201503.p','Arg201503.p')

No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
Success.
en
No text found.
No text found.
Success.
error
No text found.
Success.
ru
No text found.
Success.
ru
Success.
es
Success.
es
Success.
es
Success.
es
Success.
hu
No text found.
Success.
es
Success.
es
Success.
ar
No text found.
Success.
en
Success.
en
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
No text found.
Success.
ru
No text found.
No text found.
Success.
en
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
pt
No text found.
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
es
Success.
error
No text found.
Success.
en
Success.
en
Success.
en
Success.
en
Success.
en
Success.
en
Success.
en
Success.
en
Success.
en
Success.
es
Success.
es
Success.
es
Success.
es
No text found.
Success.
es
Success.
es
Success.
en
Success.
error
Success.
pt
No text found.
Success.
es
No text found.
Success.
es
Success.
es
No text found.
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
Success.
error
No text found.
No text found.
No text found.

In [ ]:
text_downloading('arg201504.p','Arg201504.p')
text_downloading('arg201505.p','Arg201505.p')
text_downloading('arg201506.p','Arg201506.p')
text_downloading('arg201507.p','Arg201507.p')
text_downloading('arg201508.p','Arg201509.p')
text_downloading('arg201509.p','Arg201509.p')
text_downloading('arg201510.p','Arg201510.p')
text_downloading('arg201511.p','Arg201511.p')
text_downloading('arg201512.p','Arg201512.p')
text_downloading('arg201601.p','Arg201501.p')
text_downloading('arg201602.p','Arg201501.p')
text_downloading('arg201603.p','Arg201503.p')